const pool = require('./pool');

const { Client } = require('pg')

const SQL1 = 'CREATE TABLE IF NOT EXISTS items (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), price INT)'

const SQL2 = 'CREATE TABLE IF NOT EXISTS categories (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))'

const SQL3 = 'CREATE TABLE IF NOT EXISTS item_categories_junction (item_id INT, category_id INT, PRIMARY KEY(item_id, category_id), FOREIGN KEY (item_id) REFERENCES items(id), FOREIGN KEY (category_id) REFERENCES categories(id))'

async function main(){
    console.log('Populating the database...')
    const client = new Client({
        connectionString: `postgresql://neondb_owner:${process.env.DB_USER_PASSWORD}@ep-snowy-glade-a5k650ad.us-east-2.aws.neon.tech/neondb?sslmode=require`
    })
    await client.connect();
    await client.query(SQL1);
    await client.query(SQL2);
    await client.query(SQL3);
    await client.end();
    console.log('Done!')
}

main();